/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexLazycopyImport } from './routes/index.lazy copy'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const IndexLazycopyRoute = IndexLazycopyImport.update({
  id: '/index/lazy copy',
  path: '/index/lazy copy',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/index/lazy copy': {
      id: '/index/lazy copy'
      path: '/index/lazy copy'
      fullPath: '/index/lazy copy'
      preLoaderRoute: typeof IndexLazycopyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/index/lazy copy': typeof IndexLazycopyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/index/lazy copy': typeof IndexLazycopyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/index/lazy copy': typeof IndexLazycopyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index/lazy copy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index/lazy copy'
  id: '__root__' | '/' | '/index/lazy copy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  IndexLazycopyRoute: typeof IndexLazycopyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  IndexLazycopyRoute: IndexLazycopyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/index/lazy copy"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/index/lazy copy": {
      "filePath": "index.lazy copy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
